### ISSUE TITLE
Possible to run multiple instances?

### ISSUE THREAD

**Issue by charlesvestal** [AlexSSD7/linsk#14]
Not sure if this is a bug and it should be autoincrementing the port, but I'd like to mount two different partitions to copy files between them.  On a second instance, I get 

```sudo linsk run --share-backend ftp dev:/dev/disk6 vdb2 
time=2024-03-03T09:44:03.010+01:00 level=WARN msg="Using raw block device passthrough. Please note that it's YOUR responsibility to ensure that no device is mounted in your OS and the VM at the same time. Otherwise, you run serious risks. No further warnings will be issued." caller=vm
time=2024-03-03T09:44:03.016+01:00 level=INFO msg="Booting the VM" caller=vm
time=2024-03-03T09:44:03.034+01:00 level=WARN msg="Canceling the VM context" caller=vm
time=2024-03-03T09:44:03.034+01:00 level=ERROR msg="Failed to start the VM" error="cancel on exit: interrupt cmd: no such process (qemu stderr log: '[244 chars trimmed]wd=tcp:127.0.0.1:9004-:9004,hostfwd=tcp:127.0.0.1:9005-:9005,hostfwd=tcp:127.0.0.1:9006-:9006,hostfwd=tcp:127.0.0.1:9007-:9007,hostfwd=tcp:127.0.0.1:9008-:9008,hostfwd=tcp:127.0.0.1:9009-:9009: Could not set up host forwarding rule 'tcp:127.0.0.1:9000-:21'')"
```

Is there a configuration for the afp (or smb, ftp) port mapping to allow multiple mounts at once?

**Comment by AlexSSD7** [comment]
You are right, the port should be automatically incremented. What OS is this?

(Apologies for the delayed response.)

**Comment by charlesvestal** [comment]
No worried! This was on macOS Sonoma.

**Comment by AlexSSD7** [comment]
Fixed in https://github.com/AlexSSD7/linsk/commit/750028af5ba6cb96371d838f9464a0a0c811f1cf, in the `master` branch.

I would appreciate it if you could pull the latest `master` and test it. If it works, please close the issue. (My apologies for the delayed action once again.)

**Comment by kuriot** [comment]
Hello. I just got the same problem on the latest version in Releases and the version from master branch works perfectly fine with multiple instances. Thanks!

**Comment by AlexSSD7** [comment]
@kuriot Thanks for confirming!
