### ISSUE TITLE
Nixpkgs support?

### ISSUE THREAD

**Issue by tuyenpm9** [AlexSSD7/linsk#7]
I don't find it in https://search.nixos.org/packages

Thanks for the solution.

**Comment by AlexSSD7** [comment]
Hi @tuyenpm9.

Thanks for chiming in. Unfortunately, there are no plans on getting Linsk added there as of now. Being an open-source project, you are welcome to contribute if you have the necessary skills, though.

**Comment by AlexSSD7** [comment]
Also, hold on, I just realized that NixOS is a Linux distribution.

Why would you ever need to run Linsk on Linux unless it's for development purposes (which requires building from the source anyway)?

**Comment by AlexSSD7** [comment]
Closing for now. Feel free to reopen if there is a good reason for this.

**Comment by tuyenpm9** [comment]
No, nix is a package manager and it's able to manage macOS packages also. NixOS is a Linux distro that use nix package manager. You can search for `discord` in the link and choose platform `aarch64-darwin` that is for macOS.
