### ISSUE TITLE
'qemu-system-x86_64.exe: unable to find CPU model 'host'

### ISSUE THREAD

**Issue by snowgato** [AlexSSD7/linsk#8]
Hi,
I'd like to access ext4 or lvm partitions from windows 11 on a laptop with i7-1360p processor using linsk.
VT-d is enabled in BIOS and I guess vt-x is permanently enabled( no enable/disable toggle in bios, lscpu shows vt-x in ubuntu ( dual boot ) ), hypervisor is also enabled.
I have tried to use linsk  and get the following error as typing linsk shell:

C:\Users\cedri>linsk shell
time=2023-11-14T20:32:02.792+01:00 level=WARN msg="Using unrestricted VM networking" caller=vm
time=2023-11-14T20:32:02.816+01:00 level=INFO msg="Booting the VM" caller=vm
time=2023-11-14T20:32:02.994+01:00 level=WARN msg="Canceling the VM context" caller=vm
time=2023-11-14T20:32:03.165+01:00 level=ERROR msg="Failed to start the VM" error="wait for cmd to finish execution: context canceled; cancel: interrupt cmd: exit status 128 (qemu stderr log: 'qemu-system-x86_64.exe: unable to find CPU model 'host'')"

Any idea ?
Thanks !

**Comment by AlexSSD7** [comment]
Hi, thanks for reporting.

It appears that this is a regression introduced in the last Linsk version. Please downgrade it one version back until the fix is released.

**Comment by AlexSSD7** [comment]
Hello @snowgato,

I just released Linsk v0.2.2 that fixes this issue. If you could test it and report back, I'd greatly appreciate it! Link: https://github.com/AlexSSD7/linsk/releases/tag/v0.2.2.

Closing this issue for now.
