### ISSUE TITLE
Documentation suggestions/examples: shell with passthrough and mount a luks partition

### ISSUE THREAD

**Issue by lefth** [AlexSSD7/linsk#9]
Hello. It's my first day using linsk, and I found a couple use cases that aren't covered in the documentation. I'd suggest listing them as examples, maybe in a separate file if you think the documentation is already explicit enough:

1. How to open a shell with a disk mapped (raw block device passthrough) for formatting? Answer: `linsk  shell dev:\\.\PhysicalDrive2`
2. How to mount a luks partition (not a whole disk nor LVM): ` run -l dev:\\.\PHYSICALDRIVE2 vdb1`

Also, is there a way to mount multiple disks in the same VM? I'd like to copy files and have the process be aware of Linux features like non-SMB filenames and hard links.

To clarify: I now realize that your LVM examples were intended to be the complete version of how to mount a partition, and they are also applicable to LUKS if followed carefully.

**Comment by jonathancross** [comment]
Please consider making a PR instead.
It seems that @AlexSSD7 isn't paying attention to these issues.

**Comment by AlexSSD7** [comment]
Apologies for the late response. There are not a lot of examples like this, but the overall documentation is complete. Every feature is documented, despite the lack of direct documentation for every possible feature combination.

Unfortunately, I do not have time to spare to add that. As @jonathancross pointed out, you are free to open a PR.
